- name: Debug Information
  run: |
    echo "Git version:"
    git --version
    echo "---"
    echo "Remote information:"
    git remote -v
    echo "---"
    echo "Branch information:"
    git branch -a
    echo "---"
    echo "Status:"
    git status
    echo "---"
    echo "Upstream master log:"
    git log upstream/master -n 3
    echo "---"
    echo "Local master log:"
    git log main -n 3

- name: Merge Upstream into Fork
  run: |
    git checkout main
    git merge upstream/master --no-ff -v